name: Horacio A. Vega Enríquez
favicon: null
layout_spectrum: 0.14889
typography_spectrum: 0.35222952952608466
title: 'Strive for progress, not perfection'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#447f91'
    - '#01426c'
    - '#c5cac3'
    - '#000407'
  brandStrength: 0.6993339613545686
  lightness: 0.9367754685226828
  saturation: 0.11181898601353168
  rhythmicContrast: 0.3075339321512729
purpose: []
