title: 'Strive for progress, not perfection'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1118189860135317
  brandStrength: 0.6993339613545686
  rhythmicContrast: 0.3075339321512729
  brandColors:
    - '#ffffff'
    - '#447f91'
    - '#01426c'
    - '#c5cac3'
    - '#000407'
  lightness: 0.9367754685226828
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Horacio A. Vega Enríquez
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.82808
layout_spectrum: 0.3216971
