name: Horacio A. Vega Enríquez
favicon: null
layout_spectrum: 0.7177624676842242
typography_spectrum: 0.35222952952608466
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6993339613545686
  lightness: 0.9367754685226828
  saturation: 0.11181898601353168
  rhythmicContrast: 0.3075339321512729
purpose: []
